/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface StencilWebcomponentsStart {
    'dataRaw': string;
  }
}

declare global {


  interface HTMLStencilWebcomponentsStartElement extends Components.StencilWebcomponentsStart, HTMLStencilElement {}
  var HTMLStencilWebcomponentsStartElement: {
    prototype: HTMLStencilWebcomponentsStartElement;
    new (): HTMLStencilWebcomponentsStartElement;
  };
  interface HTMLElementTagNameMap {
    'stencil-webcomponents-start': HTMLStencilWebcomponentsStartElement;
  }
}

declare namespace LocalJSX {
  interface StencilWebcomponentsStart {
    'dataRaw'?: string;
  }

  interface IntrinsicElements {
    'stencil-webcomponents-start': StencilWebcomponentsStart;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'stencil-webcomponents-start': LocalJSX.StencilWebcomponentsStart & JSXBase.HTMLAttributes<HTMLStencilWebcomponentsStartElement>;
    }
  }
}


